<a href="https://colab.research.google.com/github/isahaasasu/MAT422/blob/main/HW3_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Homework 3.7**

## Neural Networks

In [1]:
import tensorflow as tf

In [2]:
# load the dataset
mnist = tf.keras.datasets.mnist

# convert the samples from integers to floating-point numbers
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.52586174,  0.02097104,  0.21846944, -0.06984836, -0.41912735,
        -0.4027896 , -0.67178226,  0.25835475, -0.03882173, -0.29043782]],
      dtype=float32)

In [4]:
tf.nn.softmax(predictions).numpy()

array([[0.06848361, 0.11832407, 0.14416027, 0.10805149, 0.07619752,
        0.07745264, 0.05918534, 0.15002635, 0.11145651, 0.08666225]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.5580888

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2904 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1428 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1069 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0881 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 18s 10ms/step - loss: 0.0734 - accuracy: 0.9768


In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0756 - accuracy: 0.9769 - 1s/epoch - 4ms/step


[0.07562943547964096, 0.9768999814987183]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.26463767e-09, 1.57563140e-09, 7.85589691e-07, 8.23948903e-06,
        8.72112224e-13, 1.70953047e-08, 1.62499745e-15, 9.99990702e-01,
        1.09653735e-08, 2.43347415e-07],
       [6.82139137e-11, 7.30228567e-05, 9.99925852e-01, 1.08728432e-06,
        1.53600846e-13, 2.88225444e-08, 2.16631380e-09, 8.76614218e-15,
        1.77745392e-08, 9.76353279e-15],
       [8.35810738e-07, 9.99267757e-01, 2.33761777e-04, 6.36908007e-05,
        3.83359729e-05, 7.15984606e-06, 3.28955794e-05, 8.83927787e-05,
        2.63206428e-04, 3.99021110e-06],
       [9.99593437e-01, 2.34235098e-09, 1.26528721e-05, 1.10850840e-06,
        5.79326024e-06, 7.01338593e-07, 3.64831445e-04, 1.38051455e-05,
        9.86112454e-08, 7.47646527e-06],
       [2.77469530e-06, 9.30596666e-09, 7.37328264e-07, 1.24100081e-08,
        9.93946254e-01, 1.72295745e-06, 1.15300918e-05, 8.66098999e-05,
        4.85258170e-07, 5.94988652e-03]], dtype=float32)>